version: "3.1"

services:
  db:
    # platform: linux/x86_64 # Configuração para MAC-OS
    image: mysql:8.0
    restart: unless-stopped
    # && mysqld --user=root --max_connections=6000
    command: >
      --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 7WAE1#Ofne1 # root passwd
      MYSQL_DATABASE: init_db # Inital database
      MYSQL_USER: admin # New User
      MYSQL_PASSWORD: 1WAE1#Ofne2 # New User Passwd
      # MYSQL_RANDOM_ROOT_PASSWORD: "1" # Passwd random for root
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
    networks:
      - mysql

networks:
  mysql:
    driver: bridge
