version: "3.1"

services:
  db:
    # platform: linux/x86_64 # Configuração para MAC-OS
    image: mysql:8.0
    restart: unless-stopped
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_HOST: "%" # Permite conexões de qualquer host
      # MYSQL_RANDOM_ROOT_PASSWORD: "1" # Passwd random for root 
    volumes:
      - ./database.sh:/docker-entrypoint-initdb.d/database.sh
      - ./mkbase.sql:/docker-entrypoint-initdb.d/mkbase.sql
    networks:
      - mysql

networks:
  mysql:
    driver: bridge
