version: "3.1"

services:
  db:
    platform: linux/x86_64 # Configuração para MAC-OS
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 7WAE1#Ofne1 # root passwd
      MYSQL_DATABASE: init_db # Inital database
      MYSQL_USER: admin # New User
      MYSQL_PASSWORD: 7WAE1#Ofne1 # New User Passwd
      # MYSQL_RANDOM_ROOT_PASSWORD: "1" # Passwd random for root
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
      — my.cnf:/etc/mysql/My.conf
