version: "3.1"

services:
  db:
    # platform: linux/x86_64 # Configuração para MAC-OS
    image: mysql:8.0
    restart: unless-stopped
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: "7WAE1#Ofne1" # root passwd
      MYSQL_DATABASE: newproject_data # Inital database
      MYSQL_USER: admin # New User
      MYSQL_PASSWORD: "1WAE1#Ofne2" # New User Passwd
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_HOST: "%" # Permite conexões de qualquer host
      # MYSQL_RANDOM_ROOT_PASSWORD: "1" # Passwd random for root
    volumes:
      - ./database.sh:/docker-entrypoint-initdb.d/database.sh
    networks:
      - mysql

networks:
  mysql:
    driver: bridge
